# Generated by Django 4.2.23 on 2025-08-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profileview'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileview',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
