# Generated by Django 4.2.23 on 2025-08-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profileview_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationrequest',
            name='initiated_by',
            field=models.CharField(choices=[('investor', 'Investor'), ('entrepreneur', 'Entrepreneur')], default='investor', max_length=20),
        ),
    ]
